# The latest template format version is 2010-09-09 and is currently the only valid value
# as per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09

# The value for the description declaration must be a literal string that is between 0 and 1024 bytes in length. 
# You cannot use a parameter or function to specify the description.
Description: >
    A template in order to build a two environment (staging and development) without VPC

# Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
Parameters:
  # SSH access IP address range
  SSHLocation: 
    Description: The IP address range that can be used to SSH to the Bastion hosts
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the for x.x.x.x/x.

  # EC2 key pair to be used   
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name

  # EC2 allowed instance types
  InstanceType:
    Description: EC2 allowed instance types to be used 
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - t2.small
      - t2.medium
  
  # RDS Parameter
  DBName:
    Default: MyDatabase
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBUser:
    NoEcho: 'false'
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBPassword:
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.

# Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html
Mappings:
  # Map Ubuntu AMI id to region
  AWSRegionUbuntuAMI:
    us-east-1:      # N. Virginia
      HVM64: ami-0dba2cb6798deb6d8
    ap-southeast-1: # Singapore
      HVM64: ami-0e03b8332a1d7b68a      

Resources:
  #Security Group
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref 'SSHLocation'

  # EC2
  Development:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone 
      ImageId: !FindInMap [AWSRegionUbuntuAMI, !Ref 'AWS::Region', HVM64]
      KeyName: !Ref KeyName
      InstanceType: !Ref InstanceType
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-development

  Staging:
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: !Ref AvailabilityZone
      ImageId: !FindInMap [AWSRegionUbuntuAMI, !Ref 'AWS::Region', HVM64]
      KeyName: !Ref KeyName
      InstanceType: !Ref InstanceType
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-staging

  #RDS
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref 'DBName'
      AllocatedStorage: '5'
      DBInstanceClass: db.t3.small
      Engine: postgres
      #EngineVersion: 13.2
      MasterUsername: !Ref 'DBUser'
      MasterUserPassword: !Ref 'DBPassword'
      #DBParameterGroupName: !Ref 'MyRDSParamGroup'
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot

  #MyRDSParamGroup:
    #Type: AWS::RDS::DBParameterGroup
    #Properties:
     # Family: postgres9.6
     # Description: CloudFormation Sample Database Parameter Group
      #Parameters:
      #  autocommit: '1'
       # log_statement: 'all'
      #  max_connections: '100'


# Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/metadata-section-structure.html
Metadata:
# Control the UI display when running this template from the AWS Management Console
 AWS::CloudFormation::Interface:
  ParameterGroups:
    - Label:
        default: "SSH Access"
      Parameters: 
        - KeyName
        - SSHLocation